{% set name = "neurodocker" %}
{% set version = "0.7.0" %}
{% set sha256 = "188ef624b018e20e89edbe39750cae6d020044d4abcb31d686ef3d2aa7bec70a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ReproNim/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - jinja2 >=2.0
    - pyyaml >=3.0
    - etelemetry

test:
  commands:
    - neurodocker --help

about:
  home: https://github.com/ReproNim/neurodocker
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neurodocker is a command-line program that generates custom Dockerfiles and Singularity recipes for neuroimaging and minifies existing containers.

extra:
  recipe-maintainers:
    - npavlovikj
